Replace jquery with jquery3-api plugin
jenkinsci/nodelabelparameter-plugin pull request #38
Opened 2021-07-03 10:25 UTC by MarkEWaite

## Replace jquery dependency with jquery3-api plugin

Assumes that jquery3 has enough compatibility for the Javascript needed here.

Interactive testing and test automation detected no issue with this change.  Behavior is the same as the previous releases and this removes one of the dependencies on the outdated jquery API plugin.

Would greatly appreciate a review from someone with real Javascript experience, like @uhafner.  See the Javascript source at https://github.com/jenkinsci/nodelabelparameter-plugin/blob/master/src/main/webapp/lib/nodelabel.js and the references to that source at https://github.com/jenkinsci/nodelabelparameter-plugin/blob/ea0a822f3a09423eb32eee9d5496ce7a14b4a931/src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition/config.jelly#L32 and at https://github.com/jenkinsci/nodelabelparameter-plugin/blob/ea0a822f3a09423eb32eee9d5496ce7a14b4a931/src/main/resources/org/jvnet/jenkins/plugins/nodelabelparameter/LabelParameterDefinition/config.jelly#L32

2021-07-04 14:57 UTC, uhafner requested changes
This will not work (or rephrased: if it is still working then the plugin does not require jquery3?). In order to use jQuery (from the API plugin) you need to add to the jelly view:

```
<st:adjunct includes="io.jenkins.plugins.jquery3"/>
```

(See https://github.com/jenkinsci/jquery3-api-plugin#how-to-use-the-plugin)

And in the JS code you need to replace `Q` with the variable `jQuery3`. I would recommend to add a breakpoint in the JS code and see where (and if) it actually gets invoked during the configuration. It looks somewhat strange that `Q` is used to represent jQuery (normally one would use `$`), where does `Q` come from?. 

Since the JS is quite small I wonder if we could remove the jQuery dependency completely here? @halkeye pointed out some resources recently on how to get rid from jQuery in such small snippets (example: https://tobiasahlin.com/blog/move-from-jquery-to-vanilla-javascript/). I'm using jQuery only in details views where I need some visualizing powert. But on the job (or node) configuration pages it would be helpful if we would not have a dependency to jQuery at all.

2021-07-04 15:14 UTC, halkeye commented
http://youmightnotneedjquery.com/ has some great resources

looking at https://github.com/jenkinsci/nodelabelparameter-plugin/blob/master/src/main/webapp/lib/nodelabel.js

you'd want to copy the ready function
q => document.querySelector or querySelectorAll
is => .matched
show/hide => on that page

its probably a pretty simple cutover.

2021-07-05 06:41 UTC, MarkEWaite commented
Thanks to both of you for taking the time to provide feedback @uhafner and @halkeye .  I've never done Javascript development and am not confident that I could make that transition safely or reliably, but I'll certainly consider it.  I would like to remove jquery from the dependencies in this plugin so that I could eventually remove the jquery plugin from my Jenkins installation.  The Jenkins Health Adviser warns that the JQuery plugin is "unsecure".  I assume that is because it is an outdated version of jquery that is not actively maintained upstream.

2021-07-05 22:33 UTC, halkeye commented
https://github.com/jenkinsci/nodelabelparameter-plugin/pull/39

2021-07-19 19:19 UTC, closed without merging